[project]
name = "custom-transformer"
version = "0.1.0"
description = "A simple custom transformer using torch library and has been implemented in Spring 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "nltk>=3.9.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "tokenizers>=0.21.1",
    "tqdm>=4.67.1",
]
#Torch is not on PyPi package enviroment so has to be installed manually 
[tool.pdm.source."pytorch"]
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true