[project]
name = "custom-transformer"
version = "0.1.0"
description = "A simple custom transformer using torch library. implemented in Spring 2025"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "nltk>=3.9.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "dotenv",
    "huggingface_hub",
    "tokenizers>=0.21.1",
    "tqdm>=4.67.1",
    "torch",
    "transformers>=4.0.0",
    "fsspec>=2023.1.0",
    "datasets>=2.0.0", 
    "rouge-score"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"